# COMP1521 22T1 ... a general makefile for multiple exercises

CC		 = dcc
EXERCISES	?=
CLEAN_FILES	?=

.DEFAULT_GOAL	= all
.PHONY:		all

-include *.mk

all:	${EXERCISES}

clean:
	-rm -f ${CLEAN_FILES}
